POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "email": "dream0820nv@naver.com",
  "nickname": "test2",
  "password": "testuser02"
}


###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "dream0820nv@naver.com",
  "password": "testuser02"
}

###
POST http://localhost:8080/api/auth/logout
Authorization: eyJraWQiOiJyc2EtMzA3MiIsImFsZyI6IlJTMzg0In0.eyJzdWIiOiI3MTIyMTIyMTUwODAzNTQ1MTEiLCJpc3MiOiJhdXRvZmFybWVyIiwiaWF0IjoxNzQ3NjQxNDMwLCJleHAiOjE3NDc2NDUwMzB9.UwAuilu3LncSq3o5rxH011AK_XHPoes57Ug8YFNKUQfkvL7OjDXShC5f7H8AQwtYoVgPMbXb3sjhXmRhEf3L6SAxXy2FhLaNO4uNzi5virvs_4pm9OsNh1uTe0bPnf1G0KBAJQOMC-wIAFXXHgglYXyJFnZbmlFl7rpMnJGXFuQ1YIC_BIjinZiN1Nd-n-0EqE3RQRQz0sqn0OTUN0UhjJAFaeCVoAQQ6pje3QEgm_jLyeD6tmPb7XN0Qb60tG50NlXZzjxSojSrvzZMsohDDy8ig3_rYs94OLPrjhjv5gpsYkRJr1ktsx-2pl0w0Y0BYwjawsHsPjV9MJBDavLOZmjmv_Gs9wkmIHBBiBDLeITFgmLoqnUd-Td8ojze-k-4I2RRWjyLEzdbhZfj3NqkolImF4EWD4plGR9iXoDOyvpxE8esSozzNkqJp5mNWtBfgdcDbs8VujLEYCDnl6aQJ-h7sTeMUUjm3vP_eaW-KIBvrYVGxypLxT5LvjxRLDiX
Refresh-Token: eyJraWQiOiJyc2EtMzA3MiIsImFsZyI6IlJTMzg0In0.eyJzdWIiOiI3MTIyMTIyMTUwODAzNTQ1MTEiLCJpc3MiOiJhdXRvZmFybWVyIiwiaWF0IjoxNzQ3NjQxNDMwLCJleHAiOjE3NDgyNDYyMzB9.IGfVZiyqLE7TXNhmPHS-jon0Yf6nZ0yXNRYCEPNRU9ZBs5QwvUPjwhYnRkg9hlD9-1_9SRpXMk2mg063G_nXBe4R11ZeO-0W4hctATl_zubwLj-yHEYXJ5qOXU3gk0UEKYa3730Jez-PZkwRi6iyCqwVMDiQhecZbbXAPLp0n9rhIdtzPJmDTAbjp-JUiTScXuv4Be9R4su5pfLj2o3lZyJxXaShk2nQF9ykjKPM3EWf42uUmndu5azZ29KRTvXnubtPX_YlC1q1DgaSMcCu5stDpDJ6pr6l01nsnRTV3xoHgTPrI4-7p1Q7J4EIx0xQbmxFOBzC3ov3tGQ7LCMqHbU9tIZDomq1pNm4027OMup9UXt6-qkRiR2LvyxCbJ4foe0JXaHyI0FBZfPTifdTnonqt4T7vx7BdNgW4cn7kSPZ0GmGYUpb2-vNfzkin0GsCy1IFvr5MPM1-pNJSfDDMF1RL1-hFebzKz_PEcoqCP1lq6wXVogSeYu8DIm3ojkz
Content-Type: application/json
